name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set production API URL
        run: |
          sed -i 's|https://localhost:7011/|${{ secrets.API_BASE_URL }}|g' BlazorApp1.WebAsembly/wwwroot/appsettings.json
          echo "appsettings after replacement:"
          cat BlazorApp1.WebAsembly/wwwroot/appsettings.json

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_GRASS_0791DB503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "BlazorApp1.WebAsembly"
          api_location: ""
          output_location: "wwwroot"
