name: Deploy_WASM_GHPages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore Blazor WASM dependencies
        run: dotnet restore BlazorApp1.WebAsembly/BlazorApp1.WebAsembly.csproj

      - name: Build and publish Blazor WASM
        run: dotnet publish BlazorApp1.WebAsembly/BlazorApp1.WebAsembly.csproj -c Release -o BlazorApp1.WebAsembly/publish /p:PublishTrimmed=false

      - name: Deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          tmp_dir=$(mktemp -d)

          # Clone gh-pages branch from the same repo
          git clone --branch gh-pages https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git $tmp_dir

          # Remove old content and copy new publish files
          rm -rf $tmp_dir/*
          cp -r BlazorApp1.WebAsembly/publish/* $tmp_dir/


          cd $tmp_dir
          git add --all
          git commit -m "Deploy Blazor WASM $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin gh-pages
