name: Deploy to Azure
on:
  push:
    branches:
      - master  

env:
  AZURE_WEBAPP_NAME: blazorappPractice1
  AZURE_WEBAPP_PACKAGE_PATH: '.'    
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore BlazorApp1.Endpoint/BlazorApp1.Endpoint.csproj

      - name: Build
        run: dotnet build BlazorApp1.Endpoint/BlazorApp1.Endpoint.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish BlazorApp1.Endpoint/BlazorApp1.Endpoint.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp --no-build

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp
